[package]
name = "rastreador"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.30.1", features = ["ptrace"] }
clap = { version = "4.5.46", features = ["derive"] }
serde_json = "1.0.143"
owo-colors = "4.2.2"
